[font] 
size = 22.0
[font.bold]
family = "Iosevka Comfy"
style = "Bold"
[font.bold_italic]
family = "Iosevka Comfy"
style = "Bold Italic"
[font.italic]
family = "Iosevka Comfy"
style = "Italic"
[font.normal]
family = "Iosevka Comfy"
style = "Regular"

[window]
startup_mode = "Maximized"

[env]
TERM = "alacritty"

# mellifluous
[colors]
[colors.primary]
background = "0x1c1c1c"
foreground = "0xdadada"

[colors.cursor]
text = "0x1a1a1a"
cursor = "0xbfad9e"

[colors.selection]
text = "0xc0af8c"
background = "0x2d2d2d"

[colors.normal]
black = "0x1a1a1a"
red = "0xd29393"
green = "0xb3b393"
yellow = "0xcbaa89"
blue = "0xa8a1be"
magenta = "0xb39fb0"
cyan = "0xc0af8c"
white = "0xdadada"

[colors.bright]
black = "0x5b5b5b"
red = "0xc95954"
green = "0x828040"
yellow = "0xa6794c"
blue = "0x5a6599"
magenta = "0x9c6995"
cyan = "0x74a39e"
white = "0xffffff"
